name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release:
    if: github.repository == 'braebo/pocket-shader'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v3.0.0
        with:
            version: 8.15.7

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Release or Create Release Pull Request or Do Nothing
        uses: changesets/action@v1
        with:
          version: |
            pnpm changeset version
            NEW_VERSION=$(jq -r '.version' package.json)
            jq --arg new_version "$NEW_VERSION" '.version = $new_version' jsr.json > tmp.json && mv tmp.json jsr.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to jsr
        if: steps.changesets.outputs.published == 'true'
        run: pnpx -y jsr publish
